version: '3.8'
services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./backup:/redis/data

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./backup:/data/db

  backend:
    container_name: api
    build: ./
    ports:
      - 4000:4000
    depends_on:
      - redis
      - database
    command: npm run start:prod

volumes:
  redis:
    driver: local
